CHAT_RECEIVE = "chat.receive"
GROUP_CHAT_RECEIVE = "group.chat.receive"
CHAT_STATUS = "chat.status"
MESSAGE_STATUS = "message.status"
MESSAGE_DELETE = "message.delete"
MESSAGE_STAR = "message.star"
SDP_RECEIVE = "sdp.receive"
