# Generated by Django 4.1.4 on 2022-12-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otptempdata_historicalotptempdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalotptempdata',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='otptempdata',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
