# Generated by Django 4.1.4 on 2023-01-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicaluser_bio_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='profile_pic',
            field=models.TextField(default='media/default.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='media/default.jpg', upload_to='media/profilepics'),
        ),
    ]
