# Generated by Django 4.1.4 on 2022-12-14 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='views',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
