# Generated by Django 4.1.4 on 2022-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='isStarred',
            field=models.BooleanField(default=False),
        ),
    ]
