# Generated by Django 4.1.4 on 2023-01-20 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_signallingwsclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='signallingwsclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 20, 13, 38, 39, 949098, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wsclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 20, 13, 38, 46, 936333, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
