# Generated by Django 4.1.4 on 2023-01-29 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0008_signallingwsclient_created_at_wsclient_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('conv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deleted', to='chats.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
