# Generated by Django 4.1.4 on 2023-01-29 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0009_deletedconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_convs', to=settings.AUTH_USER_MODEL),
        ),
    ]
