# Generated by Django 4.1.4 on 2023-02-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_deletedconversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replyOf',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='document',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='media',
            field=models.FileField(upload_to='status/'),
        ),
    ]
