# Generated by Django 4.1.4 on 2023-04-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_message_replyof_alter_document_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
