# Generated by Django 4.1.4 on 2023-04-15 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0015_groupchat_group_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recievers',
            new_name='receivers',
        ),
        migrations.CreateModel(
            name='GroupWSClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.groupchat')),
                ('users', models.ManyToManyField(related_name='ws_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
