# Generated by Django 4.1.4 on 2023-04-24 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0016_rename_recievers_message_receivers_groupwsclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='isArchived',
        ),
        migrations.AddField(
            model_name='conversation',
            name='archivedBy',
            field=models.ManyToManyField(related_name='archived_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='archivedBy',
            field=models.ManyToManyField(related_name='archived_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
