# Generated by Django 4.1.4 on 2023-04-24 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0017_remove_conversation_isarchived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='archivedBy',
            field=models.ManyToManyField(default=[], related_name='archived_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='archivedBy',
            field=models.ManyToManyField(default=[], related_name='archived_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
